version: '3.4'

# Services definition override for development

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-dev:${DOCKER_TAG:-latest}
    build:
      target: app_dev
    # Deploy override
    volumes:
      - ./app/app:/app
      - /app/node_modules # Remove from bind-mount for better performance
